platform :ios, '8.0'
use_frameworks!
target ‘BaseProject’ do
    pod 'MJRefresh', '~> 3.1.12'
    pod 'MJExtension', '~> 3.0.13'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.8.1’
    pod 'SVProgressHUD'
    pod 'Masonry'#约束
    pod 'IQKeyboardManager'
end
